{
 "title": "Routes Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "device",
    "query": " from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"Device\"])\n  |> distinct(column: \"Device\")\n  |> map(fn: (r) => ({device: r._value}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Connected Routes ceos1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NetworkRoutes\")\n  |> filter(fn: (r) => r[\"Device\"] == \"ceos1\")\n  |> filter(fn: (r) => r[\"RoutingProtocol\"] == \"connected\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"_value\") // Use the column name you want to count as unique\n  |> count() // Count unique values\n  |> group(columns: []) // Group by nothing to get the total count\n  |> count() // Count total values\n  |> sum(column: \"_value\") // Sum the total counts\n  |> yield(name: \"total_sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected Routes ceos2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NetworkRoutes\")\n  |> filter(fn: (r) => r[\"Device\"] == \"ceos2\")\n  |> filter(fn: (r) => r[\"RoutingProtocol\"] == \"connected\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"_value\") // Use the column name you want to count as unique\n  |> count() // Count unique values\n  |> group(columns: []) // Group by nothing to get the total count\n  |> count() // Count total values\n  |> sum(column: \"_value\") // Sum the total counts\n  |> yield(name: \"total_sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSPF External Routes ceos1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NetworkRoutes\")\n  |> filter(fn: (r) => r[\"Device\"] == \"ceos1\")\n  |> filter(fn: (r) => r[\"RoutingProtocol\"] == \"ospfexternaltype2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"_value\") // Use the column name you want to count as unique\n  |> count() // Count unique values\n  |> group(columns: []) // Group by nothing to get the total count\n  |> count() // Count total values\n  |> sum(column: \"_value\") // Sum the total counts\n  |> yield(name: \"total_sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ebgp Routes ceos2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NetworkRoutes\")\n  |> filter(fn: (r) => r[\"Device\"] == \"ceos2\")\n  |> filter(fn: (r) => r[\"RoutingProtocol\"] == \"ebgp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"_value\") // Use the column name you want to count as unique\n  |> count() // Count unique values\n  |> group(columns: []) // Group by nothing to get the total count\n  |> count() // Count total values\n  |> sum(column: \"_value\") // Sum the total counts\n  |> yield(name: \"total_sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ebgp Routes ceos1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NetworkRoutes\")\n  |> filter(fn: (r) => r[\"Device\"] == \"ceos1\")\n  |> filter(fn: (r) => r[\"RoutingProtocol\"] == \"ebgp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"_value\") // Use the column name you want to count as unique\n  |> count() // Count unique values\n  |> group(columns: []) // Group by nothing to get the total count\n  |> count() // Count total values\n  |> sum(column: \"_value\") // Sum the total counts\n  |> yield(name: \"total_sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSPF External Routes ceos2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"sq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NetworkRoutes\")\n  |> filter(fn: (r) => r[\"Device\"] == \"ceos2\")\n  |> filter(fn: (r) => r[\"RoutingProtocol\"] == \"ospfexternaltype2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"_value\") // Use the column name you want to count as unique\n  |> count() // Count unique values\n  |> group(columns: []) // Group by nothing to get the total count\n  |> count() // Count total values\n  |> sum(column: \"_value\") // Sum the total counts\n  |> yield(name: \"total_sum\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}